##Implementation copied from here - https://stavshamir.github.io/python/dockerizing-a-flask-mysql-app-with-docker-compose/

version: "2"
services:
  app:
    build: .
    links:
      - db
    ports:
      - "5000:5000"
    #builds these images first
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker_deployment/db:/docker-entrypoint-initdb.d/:ro